title: Shift
description: Shift  jobs into another process outside of the client app internal process. Monitor, stop, reset and run jobs out of band.
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
  - jekyll-mentions
